
List doctorList = [
  {
   
     "Dr.Yehia Ebeid",
     "Density",
     "Heliopolis: Ankara st. infront of cairo complex mall sherton",
     250,
     4.5,
     79.2,
    "/assets/dr.jpg",
     "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "DR. Alyaa Abd Elhameed",
    "category": "density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":"Heliopolis: 57 Hassan Aflaton stfrom ALNozzha st  ard el golf",
    "image":"assets/doctor.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

   {
    "name": "Dr. Nour El Den",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":" Al Manteqah as Sadesah, Nasr City, Cairo Governorate",
    "image":"assets/teeth.jpg",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

 {
    "name": "Dr. Ahmed Khaed",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 250.0,
    "location":" Nasr City, Cairo Governorate",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    
    "name": "Dr. Norhan el berry",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":" Masr el gdeda, Cairo Governorate",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

 {
    "name": "Dr. Ahmed Mohsin",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" HCC medical mall clinic 208 (behind air force hospital) , fifth settlement",
    "image": "assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
   {
    "name":"Dr. Daniel Hany",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":" Heliopolis: obour builidings",
    "image":  "assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
   {
    "name":"Dr. seif eldin",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 250.0,
    "location":" New cairo:north 90th",
    "image":  "assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

   {
    "name":"Dr. mohamed hamedy",
    "category": "Density",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 350.0,
    "location":" New cairo:north 90th",
    "image":  "assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
///////NEUROLOGY
  {
    "name": "Dr. Ahmed Zahran",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 600.0,
    "location":" Heliopolis: Maqrezy",
    "image":"assets/Neurology.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  
    {
    "name": "Dr. Mohamed Tawfik",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 800.0,
    "location":" Heliopolis: El merghani",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Ghada Farag",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location":" Heliopolis: El merghani",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name": "Dr. Alia Hassan",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location":" Heliopolis: El merghani",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
    {
    "name": "Dr. mohamed Ali",
    "category": "Neurology",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" Heliopolis: El merghani",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  ///////////Orthopedics
  
  {
    "name": "Dr. Baraa Hassan ",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" Heliopolis: nozha street",
    "image":"assets/Neurology.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
   {
    "name": "Dr. Hazem Mhmoud",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":" Heliopolis:Lbn elwardy",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

   {
    "name": "Dr. Hazem Shokair",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 300.0,
    "location":"Heliopolis: hegazi",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
   {
    "name": "Dr. Andrew Aghabious",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location":"Heliopolis: hegazi",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
   {
    "name": "Dr. Ahmed Galal Mansour",
    "category": "Orthopedics",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location": "Heliopolis: Nozha",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
   ///////cardiology and vascular disease

 {
    "name": "Dr. Mohamed Ramdon",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location": " Heliopolis: nozha street",
    "image":"assets/cardiology.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

  {
    "name": "Dr. sherif hussein",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 400.0,
    "location": " Heliopolis:El fayoum",
    "image":"assets/doc.PNG",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
  {
    "name":"Dr. waleed abdelfatah",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 200.0,
    "location": "Heliopolis: el sabaq street",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },

   {
    "name":"Dr. Ayman osama",
    "category": "cardiology disease",
    "rating": 3.5,
    "reviews": 93.2,
    "fees": 350.0,
    "location": " Heliopolis: Gesr El Suez",
    "image":"assets/accounts.png",
    "description": "A doctor can be found in several settings, including public health organization, group practices and  hospitals They have some of the most diverse and challenging careears available and part of a universally well-respected profession",
  },
];
